name: Thiel funding tracker schedule

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r fund_tracker/requirements.txt

      - name: Run pipeline
        env:
          CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
          ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
          VC_FIRM_NAMES: ${{ secrets.VC_FIRM_NAMES }}
        run: |
          python -m fund_tracker.cli


