name: Weekly VC Fund Tracker

on:
  schedule:
    - cron: '30 10 * * 1'  # every Monday 10:30 UTC ≈ 06:30 Eastern
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r fund_tracker/requirements.txt

      - name: Run pipeline
        env:
          CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
          ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
          VC_FIRM_NAMES: ${{ secrets.VC_FIRM_NAMES }}
        run: |
          source .venv/bin/activate
          PYTHONPATH=. python -m fund_tracker.src.cli 